site_name: CueMS Utils - FormitGo
repo_url: https://github.com/stagesoft/cuems-utils
theme:
  name: material

markdown_extensions:
  - admonition

plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: [src]
