"""FR-024b (T076) — the eight fade rules, against a real document.

The corpus sweep found **zero** coverage for every ``FadeCue`` and
``FadeProfile`` rule: no vendored document contained a fade cue, so the sweep
could not say whether those eight rules would reject anything. That is a gap in
the evidence, not a clean result, and reading it as one is the mistake this
file exists to prevent.

``cuems-utils/fade_showcase.xml`` closes it. Note **where** it was added: Phase
1, before any projection code existed, with its goldens captured by the
pre-feature harness (contracts §W1b). A golden captured after the projection
changed is generated by the very code it is meant to arbitrate — the document
would have joined the corpus already exempt from the byte-identity guarantee
every other document carries, and nothing in the suite would have said so.

Each rule is exercised twice: it **passes** on the document as authored, and
**fires** on a variant that violates it. One without the other proves nothing —
a rule that always passes and a rule that always fires both satisfy half of it.
"""

from __future__ import annotations

import copy

import pytest

from cuemsutils.cues.CuemsScript import CuemsScript
from cuemsutils.errors import ValidationError
from cuemsutils.xml.validators import RULES, enforce
from tests.support.corpus import by_relpath

DOC = by_relpath("cuems-utils/fade_showcase.xml")

#: The eight the sweep could not reach (R05–R12), by their registry names.
UNPROVEN_EIGHT = (
    "fade_action_type",
    "fade_curve_type",
    "fade_duration_positive",
    "fade_target_value_range",
    "fade_profile_type",
    "fade_profile_mode",
    "fade_profile_parameters",
    "fade_profile_parameter_value",
)


@pytest.fixture(scope="module")
def script() -> CuemsScript:
    return CuemsScript.load(DOC.path)


@pytest.fixture(scope="module")
def fade_cue(script):
    from cuemsutils.cues.FadeCue import FadeCue

    return next(c for c in script.cuelist.contents if isinstance(c, FadeCue))


@pytest.fixture(scope="module")
def fade_profiles(script):
    cue = next(c for c in script.cuelist.contents if c.get("fade_profiles"))
    return cue["fade_profiles"]


# --- the document exercises what it claims to ------------------------------


def test_the_document_carries_a_fade_cue(fade_cue):
    assert fade_cue["action_type"] == "fade_action"
    assert fade_cue["curve_type"]
    assert fade_cue["duration"]
    assert fade_cue["target_value"] is not None


def test_the_document_carries_both_fade_profile_modes(fade_profiles):
    """Preset *and* parametric, because three of the eight rules only apply to
    one of them: a document with two presets leaves ``parameters`` untouched."""
    modes = {profile["mode"] for profile in fade_profiles}
    assert modes == {"preset", "parametric"}, modes
    parametric = next(p for p in fade_profiles if p["mode"] == "parametric")
    assert parametric["parameters"], "the parametric profile carries no parameters"


@pytest.mark.parametrize("name", UNPROVEN_EIGHT)
def test_each_unproven_rule_is_registered(name):
    assert name in RULES


# --- each rule passes on the document as authored --------------------------


def test_the_document_passes_the_whole_tier(script):
    report = script.validate()
    assert not report, list(report)


@pytest.mark.parametrize(
    "name,field",
    [
        ("fade_action_type", "action_type"),
        ("fade_curve_type", "curve_type"),
        ("fade_duration_positive", "duration"),
        ("fade_target_value_range", "target_value"),
    ],
    ids=lambda value: value if isinstance(value, str) else str(value),
)
def test_each_fade_cue_rule_passes_on_the_real_value(name, field, fade_cue):
    enforce(name, fade_cue[field], fade_cue)


@pytest.mark.parametrize(
    "name,field",
    [
        ("fade_profile_type", "type"),
        ("fade_profile_mode", "mode"),
        ("fade_profile_parameters", "parameters"),
    ],
)
def test_each_fade_profile_rule_passes_on_the_real_value(
    name, field, fade_profiles
):
    for profile in fade_profiles:
        enforce(name, profile.get(field), profile)


def test_the_parameter_value_rule_passes_on_the_real_value(fade_profiles):
    parametric = next(p for p in fade_profiles if p["mode"] == "parametric")
    for parameter in parametric["parameters"]:
        enforce("fade_profile_parameter_value", parameter["parameter_value"], parameter)


# --- each rule fires on a violating variant of the same document -----------


@pytest.mark.parametrize(
    "field,value,rule",
    [
        ("action_type", "play", "fade_action_type"),
        ("curve_type", "corkscrew", "fade_curve_type"),
        ("duration", "00:00:00.000", "fade_duration_positive"),
        ("target_value", 101, "fade_target_value_range"),
    ],
    ids=["action_type", "curve_type", "duration", "target_value"],
)
def test_each_fade_cue_rule_fires_on_a_violating_variant(script, field, value, rule):
    variant = copy.deepcopy(script)
    from cuemsutils.cues.FadeCue import FadeCue

    cue = next(c for c in variant.cuelist.contents if isinstance(c, FadeCue))
    dict.__setitem__(cue, field, value)

    report = variant.validate()
    assert rule in {v.rule for v in report}, list(report)


@pytest.mark.parametrize(
    "field,value,rule",
    [
        ("type", "sideways", "fade_profile_type"),
        ("mode", "improvised", "fade_profile_mode"),
    ],
    ids=["type", "mode"],
)
def test_each_fade_profile_rule_fires_on_a_violating_variant(
    script, field, value, rule
):
    variant = copy.deepcopy(script)
    cue = next(c for c in variant.cuelist.contents if c.get("fade_profiles"))
    dict.__setitem__(cue["fade_profiles"][0], field, value)

    report = variant.validate()
    assert rule in {v.rule for v in report}, list(report)


def test_the_duplicate_parameter_rule_fires_on_a_violating_variant(script):
    variant = copy.deepcopy(script)
    cue = next(c for c in variant.cuelist.contents if c.get("fade_profiles"))
    parametric = next(p for p in cue["fade_profiles"] if p["mode"] == "parametric")
    parameter = parametric["parameters"][0]
    dict.__setitem__(
        parametric, "parameters", [parameter, copy.deepcopy(parameter)]
    )

    report = variant.validate()
    assert "fade_profile_parameters" in {v.rule for v in report}, list(report)


def test_the_parameter_value_rule_fires_on_a_violating_variant(script):
    variant = copy.deepcopy(script)
    cue = next(c for c in variant.cuelist.contents if c.get("fade_profiles"))
    parametric = next(p for p in cue["fade_profiles"] if p["mode"] == "parametric")
    dict.__setitem__(parametric["parameters"][0], "parameter_value", float("inf"))

    report = variant.validate()
    assert "fade_profile_parameter_value" in {v.rule for v in report}, list(report)


def test_the_caps_rule_fires_on_duplicate_profile_types(script):
    variant = copy.deepcopy(script)
    cue = next(c for c in variant.cuelist.contents if c.get("fade_profiles"))
    first = cue["fade_profiles"][0]
    dict.__setitem__(cue, "fade_profiles", [first, copy.deepcopy(first)])

    report = variant.validate()
    assert "fade_profile_caps" in {v.rule for v in report}, list(report)


def test_a_violating_variant_refuses_to_save(script, tmp_path):
    """The tier's effect, not only its report."""
    variant = copy.deepcopy(script)
    cue = next(c for c in variant.cuelist.contents if c.get("fade_profiles"))
    first = cue["fade_profiles"][0]
    dict.__setitem__(cue, "fade_profiles", [first, copy.deepcopy(first)])

    with pytest.raises(ValidationError):
        variant.save(tmp_path / "out.xml")
    assert not (tmp_path / "out.xml").exists()


def test_the_document_itself_still_saves(script, tmp_path):
    """The control: the variants above must differ from the document by the
    violation and nothing else."""
    target = tmp_path / "out.xml"
    script.save(target)
    assert target.exists()
